include ../common_makefile

########################################
#                                      #
#             Host section             #
#                                      #
########################################

TEST_NAME = gaussian_filter_test

HOST_AWS_SRC  =  xf_gaussian_filter_accel_aws
HOST_AWS_SRC +=  xf_gaussian_filter_tb

HOST_SDx_SRC  =  xcl2

HOST_XF_SRC  +=

########################################
#                                      #
#            Kernel section            #
#                                      #
########################################

KERNEL = xf_gaussian_filter



