########################################
#                                      #
#             Host section             #
#                                      #
########################################

TEST_NAME = gaussian_filter_test

HOST_AWS_SRC  =  xf_gaussian_filter_accel_aws
HOST_AWS_SRC +=  xf_gaussian_filter_tb

########################################
#                                      #
#            Kernel section            #
#                                      #
########################################

KERNEL = xf_gaussian_filter

########################################

include ../common_makefile



