########################################
#                                      #
#             Host section             #
#                                      #
########################################

HOST_AWS_SRC +=  xf_stereo_pipeline_accel_aws
HOST_AWS_SRC +=  xf_stereo_pipeline_tb

HOST_SDx_SRC +=  xcl2

########################################
#                                      #
#            Kernel section            #
#                                      #
########################################

KERNEL = xf_stereo_pipeline

