########################################
#                                      #
#             Host section             #
#                                      #
########################################

TEST_NAME = stereo_pipeline_test

HOST_AWS_SRC +=  xf_stereo_pipeline_accel_aws
HOST_AWS_SRC +=  xf_stereo_pipeline_tb

########################################
#                                      #
#            Kernel section            #
#                                      #
########################################

KERNEL = xf_stereo_pipeline

########################################

include ../common_makefile
